name: 'envsubst-action'
description: wrapper for envsubst
author: 'Daniel Richter'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  files:
    description: 'Files to run substitutions on'
    required: true
  variables:
    description: 'Variables that you want to replace. All if not defined.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
